name: pam-2025
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas=2.1.4
  - numpy=1.24.3
  - openpyxl=3.1.2
  - jupyter=1.0.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - pip=23.3.1
  - pip:
    - markdown==3.5.1
    - flask==2.3.3
    - black==23.9.1
    - flake8==6.1.0
    - pytest==7.4.2

# Para crear el entorno: conda env create -f environment.yml
# Para activar: conda activate pam-2025
# Para actualizar: conda env update -f environment.yml